<a href="https://colab.research.google.com/github/piabona/Dacon-Kaggle/blob/main/JEJU/%EC%A0%9C%EC%A3%BC%20%ED%8A%B9%EC%82%B0%EB%AC%BC_Scaling%EC%95%99%EC%83%81%EB%B8%94_(670_4502887314)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np
import datetime

DATA_PATH = "/content/drive/MyDrive/데이터 분석/데이콘 캐글 컴페티션/DACON 경진대회/제주 특산물가격 예측/data/"
SEED = 42

In [ ]:
train_df = pd.read_csv(f"{DATA_PATH}train.csv")
trade_df = pd.read_csv(f"{DATA_PATH}international_trade.csv")
test_df = pd.read_csv(f"{DATA_PATH}test.csv")

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59397 entries, 0 to 59396
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           59397 non-null  object
 1   timestamp    59397 non-null  object
 2   item         59397 non-null  object
 3   corporation  59397 non-null  object
 4   location     59397 non-null  object
 5   supply(kg)   59397 non-null  float64
 6   price(원/kg)  59397 non-null  float64
dtypes: float64(2), object(5)
memory usage: 3.2+ MB

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092 entries, 0 to 1091
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           1092 non-null   object
 1   timestamp    1092 non-null   object
 2   item         1092 non-null   object
 3   corporation  1092 non-null   object
 4   location     1092 non-null   object
dtypes: object(5)
memory usage: 42.8+ KB

In [ ]:
train_df['timestamp'] = pd.to_datetime(train_df['timestamp'])
train_df['year'] = train_df['timestamp'].dt.year
train_df['month'] = train_df['timestamp'].dt.month
train_df['week'] = train_df['timestamp'].dt.isocalendar().loc[:, 'week']
train_df['day'] = train_df['timestamp'].dt.day
train_df['day_of_week'] = train_df['timestamp'].dt.day_of_week
train_df['day_of_year'] = train_df['timestamp'].dt.day_of_year
train_df['sin_dayofweek'] = np.sin(2 * np.pi * (train_df['day_of_week'] + 1) / 7)
train_df['cos_dayofweek'] = np.cos(2 * np.pi * (train_df['day_of_week'] + 1) / 7)
train_df

,ID,timestamp,item,corporation,location,supply(kg),price(원/kg),year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023,2,9,27,0,58,0.781831,0.623490
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023,2,9,28,1,59,0.974928,-0.222521
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023,3,9,1,2,60,0.433884,-0.900969
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023,3,9,2,3,61,-0.433884,-0.900969
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023,3,9,3,4,62,-0.974928,-0.222521

In [ ]:
test_df['timestamp'] = pd.to_datetime(test_df['timestamp'])
test_df['year'] = test_df['timestamp'].dt.year
test_df['month'] = test_df['timestamp'].dt.month
test_df['week'] = test_df['timestamp'].dt.isocalendar().loc[:, 'week']
test_df['day'] = test_df['timestamp'].dt.day
test_df['day_of_week'] = test_df['timestamp'].dt.day_of_week
test_df['day_of_year'] = test_df['timestamp'].dt.day_of_year
test_df['sin_dayofweek'] = np.sin(2 * np.pi * (test_df['day_of_week'] + 1) / 7)
test_df['cos_dayofweek'] = np.cos(2 * np.pi * (test_df['day_of_week'] + 1) / 7)
test_df

,ID,timestamp,item,corporation,location,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek
0,TG_A_J_20230304,2023-03-04,TG,A,J,2023,3,9,4,5,63,-7.818315e-01,0.623490
1,TG_A_J_20230305,2023-03-05,TG,A,J,2023,3,9,5,6,64,-2.449294e-16,1.000000
2,TG_A_J_20230306,2023-03-06,TG,A,J,2023,3,10,6,0,65,7.818315e-01,0.623490
3,TG_A_J_20230307,2023-03-07,TG,A,J,2023,3,10,7,1,66,9.749279e-01,-0.222521
4,TG_A_J_20230308,2023-03-08,TG,A,J,2023,3,10,8,2,67,4.338837e-01,-0.900969
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,RD_F_J_20230327,2023-03-27,RD,F,J,2023,3,13,27,0,86,7.818315e-01,0.623490
1088,RD_F_J_20230328,2023-03-28,RD,F,J,2023,3,13,28,1,87,9.749279e-01,-0.222521
1089,RD_F_J_20230329,2023-03-29,RD,F,J,2023,3,13,29,2,88,4.338837e-01,-0.900969
1090,RD_F_J_20230330,2023-03-30,RD,F,J,2023,3,13,30,3,89,-4.338837e-01,-0.900969
1091,RD_F_J_20230331,2023-03-31,RD,F,J,2023,3,13,31,4,90,-9.749279e-01,-0.222521

In [ ]:
train_df.rename(columns={'supply(kg)' : 'supply', 'price(원/kg)' : 'price'}, inplace=True)
train_df

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023,2,9,27,0,58,0.781831,0.623490
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023,2,9,28,1,59,0.974928,-0.222521
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023,3,9,1,2,60,0.433884,-0.900969
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023,3,9,2,3,61,-0.433884,-0.900969
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023,3,9,3,4,62,-0.974928,-0.222521

In [ ]:
month_week_mean = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['price'].mean().reset_index()
month_week_mean = month_week_mean.rename(columns={'price' : 'month_week_mean'})
train_df = train_df.merge(month_week_mean, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_mean, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521,1106.90625
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969,1106.90625
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969,1106.90625
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521,1106.90625
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490,1106.90625

In [ ]:
month_week_max = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['price'].max().reset_index()
month_week_max = month_week_max.rename(columns={'price' : 'month_week_max'})
train_df = train_df.merge(month_week_max, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_max, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521,1106.90625,3569.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969,1106.90625,3569.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969,1106.90625,3569.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521,1106.90625,3569.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490,1106.90625,3569.0

In [ ]:
month_week_std = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['price'].std().reset_index()
month_week_std = month_week_std.rename(columns={'price' : 'month_week_std'})
train_df = train_df.merge(month_week_std, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_std, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521,1106.90625,3569.0,878.46238
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969,1106.90625,3569.0,878.46238
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969,1106.90625,3569.0,878.46238
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521,1106.90625,3569.0,878.46238
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490,1106.90625,3569.0,878.46238

In [ ]:
month_mean = train_df.groupby(['item', 'corporation', 'location', 'month'])['price'].mean().reset_index()
month_mean = month_mean.rename(columns={'price' : 'month_mean'})
train_df = train_df.merge(month_mean, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_mean, on=['item','corporation', 'location', 'month'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490,1106.90625,3569.0,878.46238,1403.858065

In [ ]:
month_max = train_df.groupby(['item', 'corporation', 'location', 'month'])['price'].max().reset_index()
month_max = month_max.rename(columns={'price' : 'month_max'})
train_df = train_df.merge(month_max, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_max, on=['item','corporation', 'location', 'month'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,1,1,1,0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,2,2,2,0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,3,3,3,-0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,4,4,4,-0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,5,5,5,-0.781831,0.623490,1106.90625,3569.0,878.46238,1403.858065,5685.0

In [ ]:
month_std = train_df.groupby(['item', 'corporation', 'location', 'month'])['price'].std().reset_index()
month_std = month_std.rename(columns={'price' : 'month_std'})
train_df = train_df.merge(month_std, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_std, on=['item','corporation', 'location', 'month'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,1,1,0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,2,2,0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,3,3,-0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,4,4,-0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,5,5,-0.781831,0.623490,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903

In [ ]:
year_month_mean = train_df.groupby(['item', 'corporation', 'location', 'month', 'year'])['price'].mean().reset_index()
year_month_mean

     item corporation location  month  year        price
0      BC           A        J      1  2019  1673.451613
1      BC           A        J      1  2020  1615.870968
2      BC           A        J      1  2021  2108.838710
3      BC           A        J      1  2022  3162.451613
4      BC           A        J      1  2023  1805.258065
...   ...         ...      ...    ...   ...          ...
1984   TG           E        S     11  2022  1094.966667
1985   TG           E        S     12  2019  1096.451613
1986   TG           E        S     12  2020  1160.645161
1987   TG           E        S     12  2021  1398.548387
1988   TG           E        S     12  2022  1577.387097

[1989 rows x 6 columns]

In [ ]:
year_month_mean['month'] = year_month_mean['month'] + 1
year_month_mean

     item corporation location  month  year        price
0      BC           A        J      2  2019  1673.451613
1      BC           A        J      2  2020  1615.870968
2      BC           A        J      2  2021  2108.838710
3      BC           A        J      2  2022  3162.451613
4      BC           A        J      2  2023  1805.258065
...   ...         ...      ...    ...   ...          ...
1984   TG           E        S     12  2022  1094.966667
1985   TG           E        S     13  2019  1096.451613
1986   TG           E        S     13  2020  1160.645161
1987   TG           E        S     13  2021  1398.548387
1988   TG           E        S     13  2022  1577.387097

[1989 rows x 6 columns]

In [ ]:
mask = year_month_mean['month'] == 13
year_month_mean.loc[mask, 'month'] = 1
year_month_mean.loc[mask, 'year'] = year_month_mean.loc[mask, 'year'] + 1
year_month_mean

     item corporation location  month  year        price
0      BC           A        J      2  2019  1673.451613
1      BC           A        J      2  2020  1615.870968
2      BC           A        J      2  2021  2108.838710
3      BC           A        J      2  2022  3162.451613
4      BC           A        J      2  2023  1805.258065
...   ...         ...      ...    ...   ...          ...
1984   TG           E        S     12  2022  1094.966667
1985   TG           E        S      1  2020  1096.451613
1986   TG           E        S      1  2021  1160.645161
1987   TG           E        S      1  2022  1398.548387
1988   TG           E        S      1  2023  1577.387097

[1989 rows x 6 columns]

In [ ]:
year_month_mean = year_month_mean.rename(columns={'price' : 'last_month_mean'})
train_df = train_df.merge(year_month_mean, on=['item','corporation', 'location', 'month', 'year'], how='left')
test_df = test_df.merge(year_month_mean, on=['item','corporation', 'location', 'month' , 'year'], how='left')

train_df

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,1,0.974928,-0.222521,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,NaN
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,2,0.433884,-0.900969,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,NaN
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,3,-0.433884,-0.900969,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,NaN
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,4,-0.974928,-0.222521,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,NaN
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,5,-0.781831,0.623490,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023,2,9,...,58,0.781831,0.623490,412.384615,531.0,53.849386,354.177305,689.0,192.959888,364.290323
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023,2,9,...,59,0.974928,-0.222521,412.384615,531.0,53.849386,354.177305,689.0,192.959888,364.290323
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023,3,9,...,60,0.433884,-0.900969,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023,3,9,...,61,-0.433884,-0.900969,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023,3,9,...,62,-0.974928,-0.222521,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143

In [ ]:
test_df

,ID,timestamp,item,corporation,location,year,month,week,day,day_of_week,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean
0,TG_A_J_20230304,2023-03-04,TG,A,J,2023,3,9,4,5,63,-7.818315e-01,0.623490,2487.800000,4538.0,1676.428208,3215.417323,10044.0,2047.942430,1955.285714
1,TG_A_J_20230305,2023-03-05,TG,A,J,2023,3,9,5,6,64,-2.449294e-16,1.000000,2487.800000,4538.0,1676.428208,3215.417323,10044.0,2047.942430,1955.285714
2,TG_A_J_20230306,2023-03-06,TG,A,J,2023,3,10,6,0,65,7.818315e-01,0.623490,2563.142857,4838.0,1579.706037,3215.417323,10044.0,2047.942430,1955.285714
3,TG_A_J_20230307,2023-03-07,TG,A,J,2023,3,10,7,1,66,9.749279e-01,-0.222521,2563.142857,4838.0,1579.706037,3215.417323,10044.0,2047.942430,1955.285714
4,TG_A_J_20230308,2023-03-08,TG,A,J,2023,3,10,8,2,67,4.338837e-01,-0.900969,2563.142857,4838.0,1579.706037,3215.417323,10044.0,2047.942430,1955.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,RD_F_J_20230327,2023-03-27,RD,F,J,2023,3,13,27,0,86,7.818315e-01,0.623490,354.761905,552.0,143.423117,332.102362,574.0,158.666708,434.857143
1088,RD_F_J_20230328,2023-03-28,RD,F,J,2023,3,13,28,1,87,9.749279e-01,-0.222521,354.761905,552.0,143.423117,332.102362,574.0,158.666708,434.857143
1089,RD_F_J_20230329,2023-03-29,RD,F,J,2023,3,13,29,2,88,4.338837e-01,-0.900969,354.761905,552.0,143.423117,332.102362,574.0,158.666708,434.857143
1090,RD_F_J_20230330,2023-03-30,RD,F,J,2023,3,13,30,3,89,-4.338837e-01,-0.900969,354.761905,552.0,143.423117,332.102362,574.0,158.666708,434.857143
1091,RD_F_J_20230331,2023-03-31,RD,F,J,2023,3,13,31,4,90,-9.749279e-01,-0.222521,354.761905,552.0,143.423117,332.102362,574.0,158.666708,434.857143

In [ ]:
month_mean = train_df.groupby(['item', 'corporation', 'location', 'month'])['price'].mean().reset_index()
month_1_mean = month_mean.loc[month_mean['month'] == 12]
month_1_mean

    item corporation location  month        price
11    BC           A        J     12  2292.362903
23    BC           A        S     12  2410.120968
35    BC           B        J     12  2014.129032
47    BC           B        S     12    79.637097
59    BC           C        J     12  2166.862903
71    BC           C        S     12    17.137097
83    BC           D        J     12  2546.209677
95    BC           E        J     12  2670.758065
107   BC           E        S     12  2748.701613
119   CB           A        J     12   421.298387
131   CB           A        S     12     0.000000
143   CB           D        J     12    40.153226
155   CB           E        J     12   223.161290
167   CB           F        J     12   198.532258
179   CR           A        J     12   708.024194
191   CR           B        J     12   366.733871
203   CR           C        J     12   425.612903
215   CR           D        J     12   967.588710
227   CR           D        S     12    32.217742
239   CR           E        J     12   950.153226
251   CR           E        S     12    64.129032
263   RD           A        J     12   364.443548
275   RD           A        S     12   306.072581
287   RD           C        S     12     0.000000
299   RD           D        J     12   188.766129
311   RD           D        S     12   294.790323
323   RD           E        J     12   140.048387
335   RD           E        S     12   147.564516
347   RD           F        J     12   563.596774
359   TG           A        J     12   968.604839
371   TG           A        S     12  1315.000000
383   TG           B        J     12  1187.483871
395   TG           B        S     12  1378.895161
407   TG           C        J     12  1448.443548
419   TG           C        S     12  1585.225806
431   TG           D        J     12  1281.516129
443   TG           D        S     12  1527.217742
455   TG           E        J     12  1230.419355
467   TG           E        S     12  1308.258065

In [ ]:
for item in train_df['item'].unique():
    for corporation in train_df['corporation'].unique():
        for location in train_df['location'].unique():
            try:
                mask_1 = (train_df['item'] == item) & (train_df['corporation'] == corporation) & (train_df['location'] == location)
                mask_2 = (month_1_mean['item'] == item) & (month_1_mean['corporation'] == corporation) & (month_1_mean['location'] == location)
                train_df[mask_1] = train_df[mask_1].fillna(month_1_mean.loc[mask_2, 'price'].values[0])
            except:
                continue

train_df

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,day_of_year,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,1,0.974928,-0.222521,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,968.604839
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,2,0.433884,-0.900969,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,968.604839
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,3,-0.433884,-0.900969,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,968.604839
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,4,-0.974928,-0.222521,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,968.604839
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,5,-0.781831,0.623490,1106.906250,3569.0,878.462380,1403.858065,5685.0,988.542903,968.604839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023,2,9,...,58,0.781831,0.623490,412.384615,531.0,53.849386,354.177305,689.0,192.959888,364.290323
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023,2,9,...,59,0.974928,-0.222521,412.384615,531.0,53.849386,354.177305,689.0,192.959888,364.290323
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023,3,9,...,60,0.433884,-0.900969,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023,3,9,...,61,-0.433884,-0.900969,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023,3,9,...,62,-0.974928,-0.222521,348.500000,574.0,192.262293,332.102362,574.0,158.666708,434.857143

In [ ]:
month_mean_supply = train_df.groupby(['item', 'corporation', 'location', 'month'])['supply'].mean().reset_index()
month_mean_supply = month_mean_supply.rename(columns={'supply' : 'month_mean_supply'})
train_df = train_df.merge(month_mean_supply, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_mean_supply, on=['item','corporation', 'location', 'month'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,sin_dayofweek,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean,month_mean_supply
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,-0.433884,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,-0.974928,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,-0.781831,0.623490,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839

In [ ]:
month_std_supply = train_df.groupby(['item', 'corporation', 'location', 'month'])['supply'].std().reset_index()
month_std_supply = month_std_supply.rename(columns={'supply' : 'month_std_supply'})
train_df = train_df.merge(month_std_supply, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_std_supply, on=['item','corporation', 'location', 'month'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,cos_dayofweek,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean,month_mean_supply,month_std_supply
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,-0.900969,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,-0.222521,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,0.623490,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794

In [ ]:
month_week_mean_supply = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['supply'].mean().reset_index()
month_week_mean_supply = month_week_mean_supply.rename(columns={'supply' : 'month_week_mean_supply'})
train_df = train_df.merge(month_week_mean_supply, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_mean_supply, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_week_mean,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,1106.90625,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3

In [ ]:
month_week_std_supply = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['supply'].std().reset_index()
month_week_std_supply = month_week_std_supply.rename(columns={'supply' : 'month_week_std_supply'})
train_df = train_df.merge(month_week_std_supply, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_std_supply, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_week_max,month_week_std,month_mean,month_max,month_std,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply,month_week_std_supply
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,3569.0,878.46238,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661

In [ ]:
train_df['total'] = train_df['supply'] * train_df['price']

month_week_mean_total = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['total'].mean().reset_index()
month_week_mean_total = month_week_mean_total.rename(columns={'total' : 'month_week_mean_total'})
train_df = train_df.merge(month_week_mean_total, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_mean_total, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_mean,month_max,month_std,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply,month_week_std_supply,total,month_week_mean_total
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,104718528.0,5.244109e+07
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,35200000.0,5.244109e+07
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,1403.858065,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,40440000.0,5.244109e+07

In [ ]:
month_week_std_total = train_df.groupby(['item', 'corporation', 'location', 'month', 'week'])['total'].std().reset_index()
month_week_std_total = month_week_std_total.rename(columns={'total' : 'month_week_std_total'})
train_df = train_df.merge(month_week_std_total, on=['item','corporation', 'location', 'month', 'week'], how='left')
test_df = test_df.merge(month_week_std_total, on=['item','corporation', 'location', 'month' , 'week'], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_max,month_std,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply,month_week_std_supply,total,month_week_mean_total,month_week_std_total
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,104718528.0,5.244109e+07,5.790161e+07
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,35200000.0,5.244109e+07,5.790161e+07
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,5685.0,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,40440000.0,5.244109e+07,5.790161e+07

In [ ]:
month_mean_total = train_df.groupby(['item', 'corporation', 'location', 'month'])['total'].mean().reset_index()
month_mean_total = month_mean_total.rename(columns={'total' : 'month_mean_total'})
train_df = train_df.merge(month_mean_total, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_mean_total, on=['item','corporation', 'location', 'month' ], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_std,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply,month_week_std_supply,total,month_week_mean_total,month_week_std_total,month_mean_total
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07,4.952021e+07
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07,4.952021e+07
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,104718528.0,5.244109e+07,5.790161e+07,4.952021e+07
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,35200000.0,5.244109e+07,5.790161e+07,4.952021e+07
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,988.542903,968.604839,29435.214839,31616.201794,35149.3,41096.586661,40440000.0,5.244109e+07,5.790161e+07,4.952021e+07

In [ ]:
month_std_total = train_df.groupby(['item', 'corporation', 'location', 'month'])['total'].std().reset_index()
month_std_total = month_std_total.rename(columns={'total' : 'month_std_total'})
train_df = train_df.merge(month_std_total, on=['item','corporation', 'location', 'month'], how='left')
test_df = test_df.merge(month_std_total, on=['item','corporation', 'location', 'month' ], how='left')

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,last_month_mean,month_mean_supply,month_std_supply,month_week_mean_supply,month_week_std_supply,total,month_week_mean_total,month_week_std_total,month_mean_total,month_std_total
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,968.604839,29435.214839,31616.201794,35149.3,41096.586661,0.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,968.604839,29435.214839,31616.201794,35149.3,41096.586661,104718528.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,968.604839,29435.214839,31616.201794,35149.3,41096.586661,35200000.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,968.604839,29435.214839,31616.201794,35149.3,41096.586661,40440000.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07

In [ ]:
trade_df = trade_df[trade_df.품목명.str.contains('감귤|브로콜리|무|당근|양배추')]
trade_df = trade_df[(trade_df.품목명 != '무화과') & (trade_df.품목명 != '방울다다기 양배추')].reset_index(drop=True)
trade_df

          기간                   품목명   수출 중량  수출 금액    수입 중량  수입 금액  무역수지
0    2019-01  꽃양배추와 브로콜리(broccoli)     160      1   638913    563  -562
1    2019-01                   양배추  184650     94   395802     90     4
2    2019-01                    당근   23150     22  7466150   2955 -2934
3    2019-01                    감귤   58368    172        0      0   172
4    2019-02  꽃양배추와 브로콜리(broccoli)     780      1   396870    399  -398
..       ...                   ...     ...    ...      ...    ...   ...
201  2023-02  꽃양배추와 브로콜리(broccoli)      24      0   332640    352  -352
202  2023-02                   양배추   13188     13   377456    104   -91
203  2023-02                    당근   22510     20  9260020   3758 -3737
204  2023-02                    순무    4000      4        2      0     4
205  2023-02                    감귤    6895     34    27765     98   -64

[206 rows x 7 columns]

In [ ]:
trade_df['year'] = trade_df['기간'].apply(lambda x : int(x[0:4]))
trade_df['month'] = trade_df['기간'].apply(lambda x : int(x[5:7]))
trade_df.drop(columns = '기간', inplace=True)
trade_df

                      품목명   수출 중량  수출 금액    수입 중량  수입 금액  무역수지  year  month
0    꽃양배추와 브로콜리(broccoli)     160      1   638913    563  -562  2019      1
1                     양배추  184650     94   395802     90     4  2019      1
2                      당근   23150     22  7466150   2955 -2934  2019      1
3                      감귤   58368    172        0      0   172  2019      1
4    꽃양배추와 브로콜리(broccoli)     780      1   396870    399  -398  2019      2
..                    ...     ...    ...      ...    ...   ...   ...    ...
201  꽃양배추와 브로콜리(broccoli)      24      0   332640    352  -352  2023      2
202                   양배추   13188     13   377456    104   -91  2023      2
203                    당근   22510     20  9260020   3758 -3737  2023      2
204                    순무    4000      4        2      0     4  2023      2
205                    감귤    6895     34    27765     98   -64  2023      2

[206 rows x 8 columns]

In [ ]:
trade_df['품목명'].unique()

array(['꽃양배추와 브로콜리(broccoli)', '양배추', '당근', '감귤', '순무'], dtype=object)

In [ ]:
train_df['item'].unique()

array(['TG', 'CR', 'CB', 'RD', 'BC'], dtype=object)

In [ ]:
lst = ['BC', 'CB', 'CR', 'TG', 'RD']
for i, item in enumerate(trade_df['품목명'].unique()):
    trade_df.loc[trade_df['품목명'] == item, '품목명'] = lst[i]

trade_df

    품목명   수출 중량  수출 금액    수입 중량  수입 금액  무역수지  year  month
0    BC     160      1   638913    563  -562  2019      1
1    CB  184650     94   395802     90     4  2019      1
2    CR   23150     22  7466150   2955 -2934  2019      1
3    TG   58368    172        0      0   172  2019      1
4    BC     780      1   396870    399  -398  2019      2
..   ..     ...    ...      ...    ...   ...   ...    ...
201  BC      24      0   332640    352  -352  2023      2
202  CB   13188     13   377456    104   -91  2023      2
203  CR   22510     20  9260020   3758 -3737  2023      2
204  RD    4000      4        2      0     4  2023      2
205  TG    6895     34    27765     98   -64  2023      2

[206 rows x 8 columns]

In [ ]:
trade_df = trade_df.rename(columns={
    '품목명': 'item',
    '수출 중량': 'out_weight',
    '수출 금액': 'out_value',
    '수입 중량': 'in_weight',
    '수입 금액': 'in_value',
    '무역수지': 'tradebalance'
})

trade_df.head()

  item  out_weight  out_value  in_weight  in_value  tradebalance  year  month
0   BC         160          1     638913       563          -562  2019      1
1   CB      184650         94     395802        90             4  2019      1
2   CR       23150         22    7466150      2955         -2934  2019      1
3   TG       58368        172          0         0           172  2019      1
4   BC         780          1     396870       399          -398  2019      2

In [ ]:
train_df = train_df.merge(trade_df, on=['year', 'month', 'item'], how='left')
test_df = test_df.merge(trade_df, on=['year', 'month', 'item'], how='left')

train_df

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,total,month_week_mean_total,month_week_std_total,month_mean_total,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance
0,TG_A_J_20190101,2019-01-01,TG,A,J,0.0,0.0,2019,1,1,...,0.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0
1,TG_A_J_20190102,2019-01-02,TG,A,J,0.0,0.0,2019,1,1,...,0.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0
2,TG_A_J_20190103,2019-01-03,TG,A,J,60601.0,1728.0,2019,1,1,...,104718528.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0
3,TG_A_J_20190104,2019-01-04,TG,A,J,25000.0,1408.0,2019,1,1,...,35200000.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0
4,TG_A_J_20190105,2019-01-05,TG,A,J,32352.0,1250.0,2019,1,1,...,40440000.0,5.244109e+07,5.790161e+07,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,RD,F,J,452440.0,468.0,2023,2,9,...,211741920.0,1.706946e+08,5.079797e+07,1.476583e+08,9.325641e+07,4000.0,4.0,2.0,0.0,4.0
59393,RD_F_J_20230228,2023-02-28,RD,F,J,421980.0,531.0,2023,2,9,...,224071380.0,1.706946e+08,5.079797e+07,1.476583e+08,9.325641e+07,4000.0,4.0,2.0,0.0,4.0
59394,RD_F_J_20230301,2023-03-01,RD,F,J,382980.0,574.0,2023,3,9,...,219830520.0,1.526513e+08,8.587015e+07,1.469691e+08,7.611450e+07,NaN,NaN,NaN,NaN,NaN
59395,RD_F_J_20230302,2023-03-02,RD,F,J,477220.0,523.0,2023,3,9,...,249586060.0,1.526513e+08,8.587015e+07,1.469691e+08,7.611450e+07,NaN,NaN,NaN,NaN,NaN
59396,RD_F_J_20230303,2023-03-03,RD,F,J,427520.0,529.0,2023,3,9,...,226158080.0,1.526513e+08,8.587015e+07,1.469691e+08,7.611450e+07,NaN,NaN,NaN,NaN,NaN

In [ ]:
train_df = train_df.fillna(0)
test_df = test_df.fillna(0)

train_df.isnull().sum().sum() , test_df.isnull().sum().sum()

(0, 0)

In [ ]:
# 품목별 평균 가격
item_mean_price = train_df.groupby('item')['price'].mean().reset_index()
item_mean_price.columns = ['item', 'item_mean_price']

train_df = train_df.merge(item_mean_price, on='item', how='left')
test_df = test_df.merge(item_mean_price, on='item', how='left')

# 법인별 평균 가격
corp_mean_price = train_df.groupby('corporation')['price'].mean().reset_index()
corp_mean_price.columns = ['corporation', 'corp_mean_price']

train_df = train_df.merge(corp_mean_price, on='corporation', how='left')
test_df = test_df.merge(corp_mean_price, on='corporation', how='left')

# 지역별 평균 가격
location_mean_price = train_df.groupby('location')['price'].mean().reset_index()
location_mean_price.columns = ['location', 'location_mean_price']

train_df = train_df.merge(location_mean_price, on='location', how='left')
test_df = test_df.merge(location_mean_price, on='location', how='left')

In [ ]:
from sklearn.preprocessing import LabelEncoder

cols = ['item', 'corporation', 'location']

for col in cols:
    enc = LabelEncoder()
    train_df[col]=enc.fit_transform(train_df[col])
    test_df[col]=enc.transform(test_df[col])

train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_mean_total,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance,item_mean_price,corp_mean_price,location_mean_price
0,TG_A_J_20190101,2019-01-01,4,0,0,0.0,0.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
1,TG_A_J_20190102,2019-01-02,4,0,0,0.0,0.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
2,TG_A_J_20190103,2019-01-03,4,0,0,60601.0,1728.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
3,TG_A_J_20190104,2019-01-04,4,0,0,25000.0,1408.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
4,TG_A_J_20190105,2019-01-05,4,0,0,32352.0,1250.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148

In [ ]:
train_df.columns

Index(['ID', 'timestamp', 'item', 'corporation', 'location', 'supply', 'price',
       'year', 'month', 'week', 'day', 'day_of_week', 'day_of_year',
       'sin_dayofweek', 'cos_dayofweek', 'month_week_mean', 'month_week_max',
       'month_week_std', 'month_mean', 'month_max', 'month_std',
       'last_month_mean', 'month_mean_supply', 'month_std_supply',
       'month_week_mean_supply', 'month_week_std_supply', 'total',
       'month_week_mean_total', 'month_week_std_total', 'month_mean_total',
       'month_std_total', 'out_weight', 'out_value', 'in_weight', 'in_value',
       'tradebalance', 'item_mean_price', 'corp_mean_price',
       'location_mean_price'],
      dtype='object')

In [ ]:
test_df.head()

,ID,timestamp,item,corporation,location,year,month,week,day,day_of_week,...,month_mean_total,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance,item_mean_price,corp_mean_price,location_mean_price
0,TG_A_J_20230304,2023-03-04,4,0,0,2023,3,9,4,5,...,10861753.7,1.059350e+07,0.0,0.0,0.0,0.0,0.0,3177.442022,1141.704458,1062.35148
1,TG_A_J_20230305,2023-03-05,4,0,0,2023,3,9,5,6,...,10861753.7,1.059350e+07,0.0,0.0,0.0,0.0,0.0,3177.442022,1141.704458,1062.35148
2,TG_A_J_20230306,2023-03-06,4,0,0,2023,3,10,6,0,...,10861753.7,1.059350e+07,0.0,0.0,0.0,0.0,0.0,3177.442022,1141.704458,1062.35148
3,TG_A_J_20230307,2023-03-07,4,0,0,2023,3,10,7,1,...,10861753.7,1.059350e+07,0.0,0.0,0.0,0.0,0.0,3177.442022,1141.704458,1062.35148
4,TG_A_J_20230308,2023-03-08,4,0,0,2023,3,10,8,2,...,10861753.7,1.059350e+07,0.0,0.0,0.0,0.0,0.0,3177.442022,1141.704458,1062.35148

In [ ]:
train_df.head()

,ID,timestamp,item,corporation,location,supply,price,year,month,week,...,month_mean_total,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance,item_mean_price,corp_mean_price,location_mean_price
0,TG_A_J_20190101,2019-01-01,4,0,0,0.0,0.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
1,TG_A_J_20190102,2019-01-02,4,0,0,0.0,0.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
2,TG_A_J_20190103,2019-01-03,4,0,0,60601.0,1728.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
3,TG_A_J_20190104,2019-01-04,4,0,0,25000.0,1408.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148
4,TG_A_J_20190105,2019-01-05,4,0,0,32352.0,1250.0,2019,1,1,...,4.952021e+07,5.091995e+07,58368.0,172.0,0.0,0.0,172.0,3177.442022,1141.704458,1062.35148

In [ ]:
train_df['total']

0                0.0
1                0.0
2        104718528.0
3         35200000.0
4         40440000.0
            ...
59392    211741920.0
59393    224071380.0
59394    219830520.0
59395    249586060.0
59396    226158080.0
Name: total, Length: 59397, dtype: float64

In [ ]:
train_cols = train_df.drop(columns=['price', 'supply','total']).columns[2:]
test_cols = test_df.columns[2:]

In [ ]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])

# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])

# from sklearn.preprocessing import RobustScaler

# scaler = RobustScaler()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])

# from sklearn.preprocessing import PowerTransformer

# scaler = PowerTransformer()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])

# from sklearn.preprocessing import MaxAbsScaler

# scaler = MaxAbsScaler()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])


# from sklearn.preprocessing import Normalizer

# scaler = Normalizer()
# train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
# test_scaled = scaler.transform(test_df.iloc[:,2:])


from sklearn.preprocessing import QuantileTransformer

scaler = QuantileTransformer()
train_scaled = scaler.fit_transform(train_df.iloc[:,2:].drop(columns = ['price','supply','total']))
test_scaled = scaler.transform(test_df.iloc[:,2:])

In [ ]:
train_scaled = pd.DataFrame(train_scaled)
test_scaled = pd.DataFrame(test_scaled)

train_scaled.columns = train_cols
test_scaled.columns = test_cols

In [ ]:
train_tmp = train_df[['ID','timestamp','price','supply','total']]
test_tmp = test_df[['ID','timestamp']]

train_df = pd.concat([train_tmp,pd.DataFrame(train_scaled)], axis=1)
test_df = pd.concat([test_tmp,pd.DataFrame(test_scaled)], axis=1)

In [ ]:
target = train_df['price']
target

0           0.0
1           0.0
2        1728.0
3        1408.0
4        1250.0
          ...
59392     468.0
59393     531.0
59394     574.0
59395     523.0
59396     529.0
Name: price, Length: 59397, dtype: float64

In [ ]:
train_df['item_id'] = train_df.ID.str[0:6]
train_df

,ID,timestamp,price,supply,total,item,corporation,location,year,month,...,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance,item_mean_price,corp_mean_price,location_mean_price,item_id
0,TG_A_J_20190101,2019-01-01,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.000000,...,0.939940,0.837337,0.879880,0.000000,0.0,0.889389,1.000000,0.601101,0.0,TG_A_J
1,TG_A_J_20190102,2019-01-02,0.0,0.0,0.0,1.000000,0.0,0.0,0.0,0.000000,...,0.939940,0.837337,0.879880,0.000000,0.0,0.889389,1.000000,0.601101,0.0,TG_A_J
2,TG_A_J_20190103,2019-01-03,1728.0,60601.0,104718528.0,1.000000,0.0,0.0,0.0,0.000000,...,0.939940,0.837337,0.879880,0.000000,0.0,0.889389,1.000000,0.601101,0.0,TG_A_J
3,TG_A_J_20190104,2019-01-04,1408.0,25000.0,35200000.0,1.000000,0.0,0.0,0.0,0.000000,...,0.939940,0.837337,0.879880,0.000000,0.0,0.889389,1.000000,0.601101,0.0,TG_A_J
4,TG_A_J_20190105,2019-01-05,1250.0,32352.0,40440000.0,1.000000,0.0,0.0,0.0,0.000000,...,0.939940,0.837337,0.879880,0.000000,0.0,0.889389,1.000000,0.601101,0.0,TG_A_J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59392,RD_F_J_20230227,2023-02-27,468.0,452440.0,211741920.0,0.640641,1.0,0.0,1.0,0.153153,...,0.990490,0.508509,0.441942,0.405906,0.0,0.731732,0.230731,0.000000,0.0,RD_F_J
59393,RD_F_J_20230228,2023-02-28,531.0,421980.0,224071380.0,0.640641,1.0,0.0,1.0,0.153153,...,0.990490,0.508509,0.441942,0.405906,0.0,0.731732,0.230731,0.000000,0.0,RD_F_J
59394,RD_F_J_20230301,2023-03-01,574.0,382980.0,219830520.0,0.640641,1.0,0.0,1.0,0.236236,...,0.973974,0.000000,0.000000,0.000000,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
59395,RD_F_J_20230302,2023-03-02,523.0,477220.0,249586060.0,0.640641,1.0,0.0,1.0,0.236236,...,0.973974,0.000000,0.000000,0.000000,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
59396,RD_F_J_20230303,2023-03-03,529.0,427520.0,226158080.0,0.640641,1.0,0.0,1.0,0.236236,...,0.973974,0.000000,0.000000,0.000000,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J

In [ ]:
test_df['item_id'] = test_df.ID.str[0:6]
test_df

,ID,timestamp,item,corporation,location,year,month,week,day,day_of_week,...,month_std_total,out_weight,out_value,in_weight,in_value,tradebalance,item_mean_price,corp_mean_price,location_mean_price,item_id
0,TG_A_J_20230304,2023-03-04,1.000000,0.0,0.0,1.0,0.236236,0.194695,0.118118,0.790791,...,0.780280,0.0,0.0,0.0,0.0,0.608108,1.000000,0.601101,0.0,TG_A_J
1,TG_A_J_20230305,2023-03-05,1.000000,0.0,0.0,1.0,0.236236,0.194695,0.151151,1.000000,...,0.780280,0.0,0.0,0.0,0.0,0.608108,1.000000,0.601101,0.0,TG_A_J
2,TG_A_J_20230306,2023-03-06,1.000000,0.0,0.0,1.0,0.236236,0.214715,0.185185,0.000000,...,0.780280,0.0,0.0,0.0,0.0,0.608108,1.000000,0.601101,0.0,TG_A_J
3,TG_A_J_20230307,2023-03-07,1.000000,0.0,0.0,1.0,0.236236,0.214715,0.218719,0.215716,...,0.780280,0.0,0.0,0.0,0.0,0.608108,1.000000,0.601101,0.0,TG_A_J
4,TG_A_J_20230308,2023-03-08,1.000000,0.0,0.0,1.0,0.236236,0.214715,0.249750,0.359860,...,0.780280,0.0,0.0,0.0,0.0,0.608108,1.000000,0.601101,0.0,TG_A_J
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,RD_F_J_20230327,2023-03-27,0.640641,1.0,0.0,1.0,0.236236,0.269770,0.863864,0.000000,...,0.973974,0.0,0.0,0.0,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
1088,RD_F_J_20230328,2023-03-28,0.640641,1.0,0.0,1.0,0.236236,0.269770,0.897898,0.215716,...,0.973974,0.0,0.0,0.0,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
1089,RD_F_J_20230329,2023-03-29,0.640641,1.0,0.0,1.0,0.236236,0.269770,0.929930,0.359860,...,0.973974,0.0,0.0,0.0,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
1090,RD_F_J_20230330,2023-03-30,0.640641,1.0,0.0,1.0,0.236236,0.269770,0.961962,0.503504,...,0.973974,0.0,0.0,0.0,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J
1091,RD_F_J_20230331,2023-03-31,0.640641,1.0,0.0,1.0,0.236236,0.269770,1.000000,0.646146,...,0.973974,0.0,0.0,0.0,0.0,0.608108,0.230731,0.000000,0.0,RD_F_J

In [ ]:
train_dropcols = ['ID', 'supply']
test_dropcols = ['ID']

In [ ]:
train_ft = train_df.drop(columns = train_dropcols)
test_ft = test_df.drop(columns = test_dropcols)

In [ ]:
# !pip install autogluon

In [ ]:
# !pip install --upgrade urllib3 pyOpenSSL

In [ ]:
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor

data = TimeSeriesDataFrame(train_ft)
predictor = TimeSeriesPredictor(
    prediction_length=28,
    target="price",
    eval_metric="RMSE"
)
# seed 고정
predictor.fit(data, random_seed=SEED, presets="best_quality", time_limit=3600*3.5, hyperparameter_tune_kwargs={'num_trials': 20,
                                'scheduler': 'local',
                                'searcher': 'auto'})

================ TimeSeriesPredictor ================
TimeSeriesPredictor.fit() called
Setting presets to: best_quality
Fitting with arguments:
{'enable_ensemble': True,
 'evaluation_metric': 'RMSE',
 'excluded_model_types': None,
 'hyperparameter_tune_kwargs': {'num_trials': 20,
                                'scheduler': 'local',
                                'searcher': 'auto'},
 'hyperparameters': 'best_quality',
 'num_val_windows': 1,
 'prediction_length': 28,
 'random_seed': 42,
 'target': 'price',
 'time_limit': 12600.0,
 'verbosity': 2}
Provided training data set with 59397 rows, 39 items (item = single time series). Average time series length is 1523.0. Data frequency is 'D'.
=====================================================
INFO:lightning_fabric.utilities.seed:Global seed set to 42
AutoGluon will save models to AutogluonModels/ag-20231119_045453/
AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being 'higher is better'. The reported score can be multiplied by -1 to get the metric value.

Provided dataset contains following columns:
	target:           'price'
	past covariates:  ['total', 'item', 'corporation', 'location', 'year', 'month', 'week', 'day', 'day_of_week', 'day_of_year', 'sin_dayofweek', 'cos_dayofweek', 'month_week_mean', 'month_week_max', 'month_week_std', 'month_mean', 'month_max', 'month_std', 'last_month_mean', 'month_mean_supply', 'month_std_supply', 'month_week_mean_supply', 'month_week_std_supply', 'month_week_mean_total', 'month_week_std_total', 'month_mean_total', 'month_std_total', 'out_weight', 'out_value', 'in_weight', 'in_value', 'tradebalance', 'item_mean_price', 'corp_mean_price', 'location_mean_price']

Starting training. Start time is 2023-11-19 04:54:53
Models that will be trained: ['Naive', 'SeasonalNaive', 'Theta', 'AutoETS', 'RecursiveTabular', 'DeepAR', 'TemporalFusionTransformer', 'PatchTST', 'DirectTabular', 'AutoARIMA']
Hyperparameter tuning model: Naive. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-997.0634     = Validation score (-RMSE)
	0.08    s     = Training runtime
	0.14    s     = Validation (prediction) runtime
Hyperparameter tuning model: SeasonalNaive. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-843.9258     = Validation score (-RMSE)
	0.07    s     = Training runtime
	0.12    s     = Validation (prediction) runtime
Hyperparameter tuning model: Theta. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-838.8347     = Validation score (-RMSE)
	0.10    s     = Training runtime
	34.92   s     = Validation (prediction) runtime
Hyperparameter tuning model: AutoETS. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-797.0592     = Validation score (-RMSE)
	0.12    s     = Training runtime
	38.11   s     = Validation (prediction) runtime
Hyperparameter tuning model: RecursiveTabular. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-810.2952     = Validation score (-RMSE)
	110.49  s     = Training runtime
	2.36    s     = Validation (prediction) runtime
Hyperparameter tuning model: DeepAR. Tuning model for up to 1259.99s of the 12599.92s remaining.

  0%|          | 0/20 [00:00<?, ?it/s]

	Trained 9 models while tuning DeepAR.
	-726.4554     = Validation score (-RMSE)
	1155.43 s     = Total tuning time
Hyperparameter tuning model: TemporalFusionTransformer. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-773.0452     = Validation score (-RMSE)
	426.17  s     = Training runtime
	0.22    s     = Validation (prediction) runtime
Hyperparameter tuning model: PatchTST. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-1016.1151    = Validation score (-RMSE)
	119.32  s     = Training runtime
	0.28    s     = Validation (prediction) runtime
Hyperparameter tuning model: DirectTabular. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-977.5029     = Validation score (-RMSE)
	81.09   s     = Training runtime
	0.81    s     = Validation (prediction) runtime
Hyperparameter tuning model: AutoARIMA. Tuning model for up to 1259.99s of the 12599.92s remaining.
	-850.8046     = Validation score (-RMSE)
	0.10    s     = Training runtime
	300.79  s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	-697.6300     = Validation score (-RMSE)
	8.42    s     = Training runtime
	3.15    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'Theta', 'AutoETS', 'RecursiveTabular', 'DeepAR/T1', 'DeepAR/T2', 'DeepAR/T3', 'DeepAR/T4', 'DeepAR/T5', 'DeepAR/T6', 'DeepAR/T7', 'DeepAR/T8', 'DeepAR/T9', 'TemporalFusionTransformer', 'PatchTST', 'DirectTabular', 'AutoARIMA', 'WeightedEnsemble']
Total runtime: 2279.63 s
Best model: WeightedEnsemble
Best model score: -697.6300

In [ ]:
predictor.get_model_names()

['Naive',
 'SeasonalNaive',
 'Theta',
 'AutoETS',
 'RecursiveTabular',
 'DeepAR/T1',
 'DeepAR/T2',
 'DeepAR/T3',
 'DeepAR/T4',
 'DeepAR/T5',
 'DeepAR/T6',
 'DeepAR/T7',
 'DeepAR/T8',
 'DeepAR/T9',
 'TemporalFusionTransformer',
 'PatchTST',
 'DirectTabular',
 'AutoARIMA',
 'WeightedEnsemble']

In [ ]:
predictor.refit_full()

	WARNING: refit_full functionality for TimeSeriesPredictor is experimental and is not yet supported by all models.
Refitting models via `refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix '_FULL' and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `fit` call.
Fitting model: Naive_FULL | Skipping fit via cloning parent ...
Fitting model: SeasonalNaive_FULL | Skipping fit via cloning parent ...
Fitting model: Theta_FULL | Skipping fit via cloning parent ...
Fitting model: AutoETS_FULL | Skipping fit via cloning parent ...
Fitting model: RecursiveTabular_FULL
	63.83   s     = Training runtime
Fitting model: DeepAR/T1_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T2_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T3_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T4_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T5_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T6_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T7_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T8_FULL | Skipping fit via cloning parent ...
Fitting model: DeepAR/T9_FULL | Skipping fit via cloning parent ...
Fitting model: TemporalFusionTransformer_FULL | Skipping fit via cloning parent ...
Fitting model: PatchTST_FULL | Skipping fit via cloning parent ...
Fitting model: DirectTabular_FULL
	83.44   s     = Training runtime
Fitting model: AutoARIMA_FULL | Skipping fit via cloning parent ...
Fitting model: WeightedEnsemble_FULL | Skipping fit via cloning parent ...
Refit complete. Models trained: ['Naive_FULL', 'SeasonalNaive_FULL', 'Theta_FULL', 'AutoETS_FULL', 'RecursiveTabular_FULL', 'DeepAR/T1_FULL', 'DeepAR/T2_FULL', 'DeepAR/T3_FULL', 'DeepAR/T4_FULL', 'DeepAR/T5_FULL', 'DeepAR/T6_FULL', 'DeepAR/T7_FULL', 'DeepAR/T8_FULL', 'DeepAR/T9_FULL', 'TemporalFusionTransformer_FULL', 'PatchTST_FULL', 'DirectTabular_FULL', 'AutoARIMA_FULL', 'WeightedEnsemble_FULL']
Total runtime: 148.12 s
Updated best model to 'WeightedEnsemble_FULL' (Previously 'WeightedEnsemble'). AutoGluon will default to using 'WeightedEnsemble_FULL' for predict().

{'Naive': 'Naive_FULL',
 'SeasonalNaive': 'SeasonalNaive_FULL',
 'Theta': 'Theta_FULL',
 'AutoETS': 'AutoETS_FULL',
 'RecursiveTabular': 'RecursiveTabular_FULL',
 'DeepAR/T1': 'DeepAR/T1_FULL',
 'DeepAR/T2': 'DeepAR/T2_FULL',
 'DeepAR/T3': 'DeepAR/T3_FULL',
 'DeepAR/T4': 'DeepAR/T4_FULL',
 'DeepAR/T5': 'DeepAR/T5_FULL',
 'DeepAR/T6': 'DeepAR/T6_FULL',
 'DeepAR/T7': 'DeepAR/T7_FULL',
 'DeepAR/T8': 'DeepAR/T8_FULL',
 'DeepAR/T9': 'DeepAR/T9_FULL',
 'TemporalFusionTransformer': 'TemporalFusionTransformer_FULL',
 'PatchTST': 'PatchTST_FULL',
 'DirectTabular': 'DirectTabular_FULL',
 'AutoARIMA': 'AutoARIMA_FULL',
 'WeightedEnsemble': 'WeightedEnsemble_FULL'}

In [ ]:
predictor.get_model_names()

['Naive',
 'SeasonalNaive',
 'Theta',
 'AutoETS',
 'RecursiveTabular',
 'DeepAR/T1',
 'DeepAR/T2',
 'DeepAR/T3',
 'DeepAR/T4',
 'DeepAR/T5',
 'DeepAR/T6',
 'DeepAR/T7',
 'DeepAR/T8',
 'DeepAR/T9',
 'TemporalFusionTransformer',
 'PatchTST',
 'DirectTabular',
 'AutoARIMA',
 'WeightedEnsemble',
 'Naive_FULL',
 'SeasonalNaive_FULL',
 'Theta_FULL',
 'AutoETS_FULL',
 'RecursiveTabular_FULL',
 'DeepAR/T1_FULL',
 'DeepAR/T2_FULL',
 'DeepAR/T3_FULL',
 'DeepAR/T4_FULL',
 'DeepAR/T5_FULL',
 'DeepAR/T6_FULL',
 'DeepAR/T7_FULL',
 'DeepAR/T8_FULL',
 'DeepAR/T9_FULL',
 'TemporalFusionTransformer_FULL',
 'PatchTST_FULL',
 'DirectTabular_FULL',
 'AutoARIMA_FULL',
 'WeightedEnsemble_FULL']

In [ ]:
data = data.astype(float)

In [ ]:

pred = predictor.predict(data, random_seed=SEED, model='WeightedEnsemble_FULL')
pred

INFO:lightning_fabric.utilities.seed:Global seed set to 42

                           mean          0.1          0.2          0.3  \
item_id timestamp
TG_A_J  2023-03-04  3367.814960  1788.986431  2382.109230  2760.363223
        2023-03-05   373.118067  -743.588039  -359.212286   -77.416461
        2023-03-06  3439.449521  1025.398775  1919.383839  2472.202580
        2023-03-07  3434.124203   951.994245  1883.738622  2491.903408
        2023-03-08  3333.559220   590.474121  1661.141869  2335.270186
...                         ...          ...          ...          ...
RD_F_J  2023-03-27   541.038694    98.417140   258.002145   373.196443
        2023-03-28   543.058420    71.835198   264.119441   372.316718
        2023-03-29   538.059131    51.612278   257.678254   371.753794
        2023-03-30   532.864598    47.191625   240.416781   363.193156
        2023-03-31   545.809894    58.384154   239.676654   369.771178

                            0.4          0.5          0.6          0.7  \
item_id timestamp
TG_A_J  2023-03-04  3071.954170  3308.645770  3589.288116  3961.093906
        2023-03-05   150.897266   371.774682   589.893027   833.308349
        2023-03-06  2918.506572  3342.499326  3783.939405  4285.405447
        2023-03-07  3032.053258  3457.597470  3964.762715  4468.386563
        2023-03-08  2894.806442  3390.040787  3895.981797  4445.033251
...                         ...          ...          ...          ...
RD_F_J  2023-03-27   454.134031   528.685820   615.008154   707.101603
        2023-03-28   462.750838   545.631113   625.487462   717.367795
        2023-03-29   458.046154   540.559680   627.466615   718.056805
        2023-03-30   451.529036   539.199163   628.100430   713.505669
        2023-03-31   456.521357   548.561328   633.710376   726.579391

                            0.8          0.9
item_id timestamp
TG_A_J  2023-03-04  4376.947448  4912.894404
        2023-03-05  1110.909813  1490.772118
        2023-03-06  4862.216375  5617.536400
        2023-03-07  5108.026325  6116.798412
        2023-03-08  5168.936043  6270.348878
...                         ...          ...
RD_F_J  2023-03-27   810.709895  1000.536420
        2023-03-28   828.328904   997.689857
        2023-03-29   825.543179  1003.545317
        2023-03-30   823.531418   997.988709
        2023-03-31   849.014941  1013.450122

[1092 rows x 10 columns]

In [ ]:
pred.to_csv('pred_Quantile_scaling_1119.csv', index=False)

# 앙상블 작업

In [ ]:


original = pd.read_csv('pred_autogluon_v100_1117.csv')

minmax = pd.read_csv('pred_MinMax_scaling_1119.csv')
standard = pd.read_csv('pred_standard_scaling_1119.csv')
robust = pd.read_csv('pred_Robust_scaling_1119.csv')
powertrans = pd.read_csv('pred_PowerTransformer_scaling_1119.csv')
maxabs = pd.read_csv('pred_MaxAbs_scaling_1119.csv')
normalizer = pd.read_csv('pred_Normalizer_scaling_1119.csv')
quantile = pd.read_csv('pred_Quantile_scaling_1119.csv')

In [ ]:
original['mean']

0       3242.523713
1        389.450981
2       3255.184581
3       3395.988407
4       3314.301545
           ...
1087     513.469446
1088     515.985473
1089     516.326125
1090     509.636177
1091     538.450092
Name: mean, Length: 1092, dtype: float64

In [ ]:
minmax['mean']

0       3315.378695
1        436.762205
2       3313.630526
3       3379.294037
4       3349.902017
           ...
1087     535.725814
1088     532.278244
1089     528.196980
1090     520.120286
1091     539.599810
Name: mean, Length: 1092, dtype: float64

In [ ]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
submission = pd.read_csv('sample_submission.csv')

In [ ]:
train_df.rename(columns={'supply(kg)' : 'supply', 'price(원/kg)' : 'price'}, inplace=True)
train_df['timestamp'] = pd.to_datetime(train_df['timestamp'])
train_df['year'] = train_df['timestamp'].dt.year
train_df['month'] = train_df['timestamp'].dt.month
min_df = train_df[train_df['price'] != 0].groupby(['item', 'corporation', 'location', 'month'])['price'].min().reset_index()
min_df = min_df[min_df['month'] == 3]
min_df.drop(columns=['month'], inplace=True)
min_df = min_df.reset_index(drop=True)
min_df

   item corporation location   price
0    BC           A        J  1796.0
1    BC           A        S  1597.0
2    BC           B        J  1120.0
3    BC           B        S  2000.0
4    BC           C        J   205.0
5    BC           C        S  2250.0
6    BC           D        J  1399.0
7    BC           E        J  1499.0
8    BC           E        S   922.0
9    CB           A        J   206.0
10   CB           A        S   313.0
11   CB           D        J   275.0
12   CB           E        J   200.0
13   CB           F        J   284.0
14   CR           A        J   450.0
15   CR           B        J   585.0
16   CR           C        J   590.0
17   CR           D        J   557.0
18   CR           D        S   615.0
19   CR           E        J   500.0
20   CR           E        S   747.0
21   RD           A        J   124.0
22   RD           A        S   149.0
23   RD           C        S   312.0
24   RD           D        J   200.0
25   RD           D        S   257.0
26   RD           E        J   200.0
27   RD           E        S   275.0
28   RD           F        J   244.0
29   TG           A        J   854.0
30   TG           A        S  2616.0
31   TG           B        J   910.0
32   TG           B        S  2593.0
33   TG           C        J   784.0
34   TG           C        S  2226.0
35   TG           D        J  1245.0
36   TG           D        S  2049.0
37   TG           E        J   675.0
38   TG           E        S  1875.0

In [ ]:

test_df = test_df.merge(min_df, on=['item', 'corporation', 'location'], how='left')
test_df

                   ID   timestamp item corporation location  price
0     TG_A_J_20230304  2023-03-04   TG           A        J  854.0
1     TG_A_J_20230305  2023-03-05   TG           A        J  854.0
2     TG_A_J_20230306  2023-03-06   TG           A        J  854.0
3     TG_A_J_20230307  2023-03-07   TG           A        J  854.0
4     TG_A_J_20230308  2023-03-08   TG           A        J  854.0
...               ...         ...  ...         ...      ...    ...
1087  RD_F_J_20230327  2023-03-27   RD           F        J  244.0
1088  RD_F_J_20230328  2023-03-28   RD           F        J  244.0
1089  RD_F_J_20230329  2023-03-29   RD           F        J  244.0
1090  RD_F_J_20230330  2023-03-30   RD           F        J  244.0
1091  RD_F_J_20230331  2023-03-31   RD           F        J  244.0

[1092 rows x 6 columns]

In [ ]:
original['mean_3456'] = (original['0.3'] + original['0.4'] + original['0.5'] + original['0.6'])/4

condition = original.index <= 280
original.loc[condition, 'mean_tg3456'] = original.loc[condition, 'mean_3456']
original.loc[~condition, 'mean_tg3456'] = original.loc[~condition, 'mean']

original

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3242.523713,1628.411697,2224.615351,2603.075262,2923.557794,3188.490876,3487.747657,3819.657313,4200.835516,4800.276200,3050.717897,3050.717897
1,389.450981,-841.313535,-420.726804,-115.540996,142.084244,385.830442,625.554165,883.972964,1187.564119,1608.896862,259.481964,259.481964
2,3255.184581,1008.213683,1812.431583,2330.108067,2747.430807,3161.629161,3572.638214,4025.507341,4543.177996,5303.827705,2952.951562,2952.951562
3,3395.988407,1030.075716,1899.249016,2490.816084,2950.753927,3417.226932,3865.265458,4354.035363,4885.473281,5826.442265,3181.015600,3181.015600
4,3314.301545,731.977730,1688.983599,2336.010721,2855.505995,3333.915559,3791.749561,4316.780693,4942.069106,5950.918466,3079.295459,3079.295459
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,513.469446,86.683823,237.046965,341.665470,427.863673,508.276239,585.139271,687.607754,799.173928,957.732396,465.736163,513.469446
1088,515.985473,62.260513,244.200374,345.545572,439.327055,517.350952,610.210698,698.837014,804.709369,972.215390,478.108569,515.985473
1089,516.326125,42.967683,231.574642,347.611420,433.182421,514.401717,600.004520,699.735402,814.703371,973.843525,473.800020,516.326125
1090,509.636177,45.047526,223.554424,336.714721,430.095535,507.902992,598.829200,694.714260,808.436771,987.931565,468.385612,509.636177
1091,538.450092,60.340873,219.354243,334.694059,435.355340,523.432423,610.040096,709.784099,824.217607,990.745263,475.880479,538.450092

In [ ]:
standard['mean_3456'] = (standard['0.3'] + standard['0.4'] + standard['0.5'] + standard['0.6'])/4

condition = standard.index <= 280
standard.loc[condition, 'mean_tg3456'] = standard.loc[condition, 'mean_3456']
standard.loc[~condition, 'mean_tg3456'] = standard.loc[~condition, 'mean']

standard

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3195.802138,1840.293030,2417.715302,2729.175478,3000.067468,3157.541640,3420.574161,3695.413905,3998.640927,4536.341641,3076.839687,3076.839687
1,328.366782,-233.192367,-35.929414,115.736635,226.092325,325.803086,444.139681,575.535327,711.494325,941.063433,277.942932,277.942932
2,3357.169569,1754.194356,2394.274251,2756.706596,3045.705354,3290.923109,3580.147701,3907.443578,4269.576851,4862.541450,3168.370690,3168.370690
3,3361.652601,1756.604601,2400.091844,2800.521474,3098.598057,3376.691664,3678.199089,4015.318030,4376.930033,5068.789347,3238.502571,3238.502571
4,3384.676649,1693.143958,2371.859178,2797.776892,3118.443544,3398.565199,3691.602503,4041.050284,4457.606669,5169.286001,3251.597035,3251.597035
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,596.607366,282.825734,397.139137,470.457536,538.391473,592.930074,639.498613,705.681421,785.839802,897.732733,560.319424,596.607366
1088,593.094320,270.052959,398.914819,469.105575,540.947410,594.061224,654.481587,710.892376,787.041399,904.329620,564.648949,593.094320
1089,594.782339,260.942143,392.417266,472.445175,537.420177,593.419653,648.263000,712.374859,795.271359,907.694236,562.887001,594.782339
1090,594.340231,265.559032,390.325892,468.721999,538.347096,593.112966,650.988670,712.003476,794.438844,923.193283,562.792683,594.340231
1091,614.177023,271.609769,384.763818,465.588079,539.986108,603.543035,657.542604,722.246328,805.405368,926.913847,566.664957,614.177023

In [ ]:
minmax['mean_3456'] = (minmax['0.3'] + minmax['0.4'] + minmax['0.5'] + minmax['0.6'])/4

condition = minmax.index <= 280
minmax.loc[condition, 'mean_tg3456'] = minmax.loc[condition, 'mean_3456']
minmax.loc[~condition, 'mean_tg3456'] = minmax.loc[~condition, 'mean']

minmax

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3315.378695,1976.819959,2463.244060,2757.098447,3030.096594,3273.397982,3551.959013,3874.607062,4170.128258,4591.423453,3153.138009,3153.138009
1,436.762205,-550.659868,-227.381326,16.018066,252.309512,430.745898,618.525026,829.215989,1057.766590,1390.762669,329.399626,329.399626
2,3313.630526,1523.398719,2160.471202,2567.676798,2914.418099,3240.290926,3585.380550,3984.039575,4376.150933,4963.155301,3076.941593,3076.941593
3,3379.294037,1452.056936,2157.227649,2645.385641,3034.962623,3400.044891,3776.594323,4183.285196,4640.930981,5388.056650,3214.246870,3214.246870
4,3349.902017,1266.652057,2065.134509,2555.546685,2996.723214,3377.157022,3751.781871,4198.820460,4673.949189,5513.875244,3170.302198,3170.302198
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,535.725814,106.498094,270.889741,377.370782,452.274838,530.174331,601.352649,683.250448,792.098798,941.676694,490.293150,535.725814
1088,532.278244,53.099667,273.590727,380.253397,461.145461,539.426560,618.306627,700.645895,796.588961,946.481899,499.783011,532.278244
1089,528.196980,43.179135,263.393800,378.396752,457.137407,540.783559,615.909020,701.756578,799.472665,935.963681,498.056684,528.196980
1090,520.120286,26.627547,244.784961,365.007255,452.219635,532.650208,609.566622,693.931498,787.955038,943.427509,489.860930,520.120286
1091,539.599810,42.825362,238.694098,368.531976,455.694675,546.739519,620.060777,703.564357,809.865148,964.223440,497.756737,539.599810

In [ ]:
robust['mean_3456'] = (robust['0.3'] + robust['0.4'] + robust['0.5'] + robust['0.6'])/4

condition = robust.index <= 280
robust.loc[condition, 'mean_tg3456'] = robust.loc[condition, 'mean_3456']
robust.loc[~condition, 'mean_tg3456'] = robust.loc[~condition, 'mean']

robust

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3411.693436,1759.402273,2392.529839,2800.151710,3090.596191,3389.864212,3665.600006,4032.858422,4416.701453,4953.962778,3236.553030,3236.553030
1,517.335504,-801.115275,-344.083148,-24.372003,253.734998,516.164479,761.568762,1045.163979,1363.119448,1802.391999,376.774059,376.774059
2,3294.778321,979.098798,1860.662687,2411.370107,2858.640774,3296.965454,3698.027989,4187.172740,4764.008883,5521.878650,3066.251081,3066.251081
3,3451.209051,952.185229,1887.987724,2518.053030,3002.931982,3506.808111,3959.184424,4514.395560,5107.043751,5995.700983,3246.744387,3246.744387
4,3428.007125,567.345111,1663.038082,2366.663042,2929.120231,3449.510238,3957.456396,4553.917095,5206.855410,6265.054179,3175.687477,3175.687477
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,565.964647,61.831496,250.945330,371.545071,472.460893,567.360220,658.285784,766.369259,878.021001,1060.776045,517.412992,565.964647
1088,556.124457,52.032858,250.377567,380.278476,485.824114,574.210601,668.459991,767.234545,886.616675,1068.108089,527.193295,556.124457
1089,568.443115,1.043364,239.281939,371.469522,475.295169,572.110184,666.831776,767.108157,889.743055,1081.383853,521.426663,568.443115
1090,546.662196,-12.170372,216.399006,351.118243,459.204098,553.704734,658.393316,764.130672,891.321917,1085.119316,505.605098,546.662196
1091,557.000617,-40.249486,216.759283,356.846180,460.523971,563.384860,664.713518,770.842874,914.910896,1106.746878,511.367132,557.000617

In [ ]:
powertrans['mean_3456'] = (powertrans['0.2'] + powertrans['0.3'] + powertrans['0.4'] + powertrans['0.5'] + powertrans['0.6'])/5

condition = powertrans.index <= 280
powertrans.loc[condition, 'mean_tg3456'] = powertrans.loc[condition, 'mean_3456']
powertrans.loc[~condition, 'mean_tg3456'] = powertrans.loc[~condition, 'mean']

powertrans

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3351.453954,1762.860642,2459.047598,2852.932130,3115.722519,3336.748410,3551.028868,3841.301018,4156.092529,4610.226684,3063.095905,3063.095905
1,486.235949,-415.023643,-95.491440,132.183006,315.363387,483.437693,661.192496,854.924097,1063.188319,1362.346392,299.337029,299.337029
2,3329.047395,1315.725964,2168.852852,2639.882066,3034.610484,3348.552903,3674.312608,4081.942706,4542.531513,5190.031588,2973.242183,2973.242183
3,3463.797183,1207.254423,2163.157840,2687.916866,3119.273773,3503.743096,3866.063784,4296.403625,4815.495524,5561.098424,3068.031072,3068.031072
4,3502.263320,1006.504201,2080.930696,2661.015936,3136.131762,3520.706418,3936.071998,4391.870430,4926.526192,5769.445687,3066.971362,3066.971362
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,647.881428,181.952593,376.816752,479.564817,574.492609,651.616002,731.024903,805.900041,905.265818,1053.889504,562.703016,647.881428
1088,629.403927,93.039415,359.185956,488.555719,585.622867,656.578011,730.586104,801.437546,900.754666,1042.937118,564.105732,629.403927
1089,652.940710,93.212164,347.157074,489.070001,593.674616,667.668605,749.638277,817.169973,910.868032,1078.749484,569.441715,652.940710
1090,629.041434,81.686420,329.551145,472.140796,586.973141,656.738107,741.481871,818.811317,924.004001,1073.786247,557.377012,629.041434
1091,650.588462,73.469697,326.628365,477.408232,584.737798,663.801048,750.798858,827.282827,935.126279,1095.838604,560.674860,650.588462

In [ ]:
maxabs['mean_3456'] = (maxabs['0.3'] + maxabs['0.4'] + maxabs['0.5'] + maxabs['0.6'])/4

condition = maxabs.index <= 280
maxabs.loc[condition, 'mean_tg3456'] = maxabs.loc[condition, 'mean_3456']
maxabs.loc[~condition, 'mean_tg3456'] = maxabs.loc[~condition, 'mean']

maxabs

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3338.129641,1686.447083,2372.041671,2771.455755,3039.232247,3320.032351,3572.821683,3916.150298,4304.829275,4825.595570,3175.885509,3175.885509
1,409.130303,-718.154024,-322.681598,-29.772093,184.588366,407.514057,622.030941,861.953072,1135.781311,1521.869784,296.090318,296.090318
2,3305.801972,1120.927428,1961.762763,2484.771771,2898.358280,3290.269288,3695.922620,4114.964437,4673.620035,5370.291293,3092.330490,3092.330490
3,3466.860215,996.699186,2007.529322,2596.389976,3066.975033,3515.053086,3954.643560,4411.103952,4993.112724,5814.361347,3283.265414,3283.265414
4,3414.618687,718.142479,1772.907191,2443.298275,2961.987404,3428.732274,3926.393678,4429.322888,5068.069976,6011.144365,3190.102908,3190.102908
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,530.169519,77.867517,237.539981,349.857736,440.708151,528.850232,615.292404,710.002691,823.828395,989.820483,483.677131,530.169519
1088,504.189301,23.084683,213.687350,343.932463,435.607228,519.522801,608.647485,695.560790,806.347441,982.160502,476.927494,504.189301
1089,518.659040,28.200178,210.040178,333.520134,427.036486,519.833570,609.310593,694.185171,816.235188,1000.921546,472.425196,518.659040
1090,494.465255,-36.236164,180.022596,315.538918,409.493108,505.766345,593.720407,696.075800,816.263520,1009.191555,456.129695,494.465255
1091,502.958215,-51.474349,184.739690,312.312866,410.167460,505.596540,597.051135,699.637923,829.961110,1023.797983,456.282000,502.958215

In [ ]:
normalizer['mean_3456'] = (normalizer['0.3'] + normalizer['0.4'] + normalizer['0.5'] + normalizer['0.6'])/4

condition = normalizer.index <= 280
normalizer.loc[condition, 'mean_tg3456'] = normalizer.loc[condition, 'mean_3456']
normalizer.loc[~condition, 'mean_tg3456'] = normalizer.loc[~condition, 'mean']

normalizer

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3384.956987,1312.377779,2090.236923,2572.611394,2970.579681,3314.804643,3682.909562,4146.796538,4620.033808,5377.362966,3135.226320,3135.226320
1,189.448250,-1369.829293,-835.907331,-446.324766,-127.788920,182.961632,484.248203,820.260297,1203.468642,1735.760222,23.274037,23.274037
2,3634.500110,881.181373,1764.712540,2359.446197,2816.682053,3296.288684,3737.941410,4293.202583,4880.483475,5727.169231,3052.589586,3052.589586
3,3329.803581,748.881628,1697.339340,2357.670298,2892.943292,3366.942863,3838.083474,4429.718058,5065.370635,6051.624173,3113.909981,3113.909981
4,3356.476649,565.674571,1615.380458,2293.616893,2854.110955,3410.028284,3906.865365,4472.053629,5186.331817,6203.370243,3116.155374,3116.155374
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,548.139749,136.722783,280.873009,386.890938,464.815513,541.422891,619.905688,709.672831,813.361190,980.453061,503.258757,548.139749
1088,545.782633,65.121276,284.266850,388.171346,471.401023,547.907114,627.984076,718.430223,817.908236,985.028566,508.865890,545.782633
1089,540.166234,75.299536,275.968331,380.233795,461.091615,543.647557,622.936455,712.807716,813.667756,975.307707,501.977356,540.166234
1090,523.747282,47.615301,256.077845,368.094295,456.940332,534.514525,622.651134,707.140647,802.465861,982.576970,495.550071,523.747282
1091,539.347496,72.211153,259.231954,372.925317,463.064213,546.661766,627.145763,715.968622,821.712713,997.053126,502.449265,539.347496

In [ ]:
quantile['mean_3456'] = (quantile['0.3'] + quantile['0.4'] + quantile['0.5'] + quantile['0.6'])/4

condition = quantile.index <= 280
quantile.loc[condition, 'mean_tg3456'] = quantile.loc[condition, 'mean_3456']
quantile.loc[~condition, 'mean_tg3456'] = quantile.loc[~condition, 'mean']

quantile

,mean,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,mean_3456,mean_tg3456
0,3367.814960,1788.986431,2382.109230,2760.363223,3071.954170,3308.645770,3589.288116,3961.093906,4376.947448,4912.894404,3182.562820,3182.562820
1,373.118067,-743.588039,-359.212286,-77.416461,150.897266,371.774682,589.893027,833.308349,1110.909813,1490.772118,258.787128,258.787128
2,3439.449521,1025.398775,1919.383839,2472.202580,2918.506572,3342.499326,3783.939405,4285.405447,4862.216375,5617.536400,3129.286971,3129.286971
3,3434.124203,951.994245,1883.738622,2491.903408,3032.053258,3457.597470,3964.762715,4468.386563,5108.026325,6116.798412,3236.579213,3236.579213
4,3333.559220,590.474121,1661.141869,2335.270186,2894.806442,3390.040787,3895.981797,4445.033251,5168.936043,6270.348878,3129.024803,3129.024803
...,...,...,...,...,...,...,...,...,...,...,...,...
1087,541.038694,98.417140,258.002145,373.196443,454.134031,528.685820,615.008154,707.101603,810.709895,1000.536420,492.756112,541.038694
1088,543.058420,71.835198,264.119441,372.316718,462.750838,545.631113,625.487462,717.367795,828.328904,997.689857,501.546533,543.058420
1089,538.059131,51.612278,257.678254,371.753794,458.046154,540.559680,627.466615,718.056805,825.543179,1003.545317,499.456561,538.059131
1090,532.864598,47.191625,240.416781,363.193156,451.529036,539.199163,628.100430,713.505669,823.531418,997.988709,495.505446,532.864598
1091,545.809894,58.384154,239.676654,369.771178,456.521357,548.561328,633.710376,726.579391,849.014941,1013.450122,502.141060,545.809894

In [ ]:
test_df['original'] = original['mean_tg3456']
test_df['minmax'] = minmax['mean_tg3456']
test_df['standard'] = standard['mean_tg3456']
test_df['robust'] = robust['mean_tg3456']
test_df['powertrans'] = powertrans['mean_3456'] # 혼자 전체 2~6 평균
test_df['maxabs'] = maxabs['mean_tg3456']
test_df['normalizer'] = normalizer['mean_tg3456']
test_df['quantile'] = quantile['mean_tg3456']

test_df['total_mean'] = original['mean_tg3456']*0.3 + minmax['mean_tg3456']*0.1 + standard['mean_tg3456']*0.1 + robust['mean_tg3456']*0.1 + powertrans['mean_3456']*0.1 + maxabs['mean_tg3456']*0.1 + normalizer['mean_tg3456']*0.1 + quantile['mean_tg3456']*0.1

test_df

,ID,timestamp,item,corporation,location,price,original,minmax,standard,robust,powertrans,maxabs,normalizer,quantile,total_mean
0,TG_A_J_20230304,2023-03-04,TG,A,J,854.0,3050.717897,3153.138009,3076.839687,3236.553030,3063.095905,3175.885509,3135.226320,3182.562820,3117.545497
1,TG_A_J_20230305,2023-03-05,TG,A,J,854.0,259.481964,329.399626,277.942932,376.774059,299.337029,296.090318,23.274037,258.787128,264.005102
2,TG_A_J_20230306,2023-03-06,TG,A,J,854.0,2952.951562,3076.941593,3168.370690,3066.251081,2973.242183,3092.330490,3052.589586,3129.286971,3041.786728
3,TG_A_J_20230307,2023-03-07,TG,A,J,854.0,3181.015600,3214.246870,3238.502571,3246.744387,3068.031072,3283.265414,3113.909981,3236.579213,3194.432631
4,TG_A_J_20230308,2023-03-08,TG,A,J,854.0,3079.295459,3170.302198,3251.597035,3175.687477,3066.971362,3190.102908,3116.155374,3129.024803,3133.772753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,RD_F_J_20230327,2023-03-27,RD,F,J,244.0,513.469446,535.725814,596.607366,565.964647,562.703016,530.169519,548.139749,541.038694,542.075714
1088,RD_F_J_20230328,2023-03-28,RD,F,J,244.0,515.985473,532.278244,593.094320,556.124457,564.105732,504.189301,545.782633,543.058420,538.658953
1089,RD_F_J_20230329,2023-03-29,RD,F,J,244.0,516.326125,528.196980,594.782339,568.443115,569.441715,518.659040,540.166234,538.059131,540.672693
1090,RD_F_J_20230330,2023-03-30,RD,F,J,244.0,509.636177,520.120286,594.340231,546.662196,557.377012,494.465255,523.747282,532.864598,529.848539
1091,RD_F_J_20230331,2023-03-31,RD,F,J,244.0,538.450092,539.599810,614.177023,557.000617,560.674860,502.958215,539.347496,545.809894,547.491819

In [ ]:
test_df.columns

Index(['ID', 'timestamp', 'item', 'corporation', 'location', 'price',
       'original', 'minmax', 'standard', 'robust', 'powertrans', 'maxabs',
       'normalizer', 'quantile', 'total_mean'],
      dtype='object')

In [ ]:
test_df.loc[ test_df['total_mean'] < test_df['price'], 'total_mean'] = 0.0
test_df.drop(columns=['item','corporation', 'location', 'price',
                      'original', 'minmax', 'standard', 'robust', 'powertrans',
                      'maxabs','normalizer','quantile'], inplace=True)

test_df

                   ID   timestamp   total_mean
0     TG_A_J_20230304  2023-03-04  3117.545497
1     TG_A_J_20230305  2023-03-05     0.000000
2     TG_A_J_20230306  2023-03-06  3041.786728
3     TG_A_J_20230307  2023-03-07  3194.432631
4     TG_A_J_20230308  2023-03-08  3133.772753
...               ...         ...          ...
1087  RD_F_J_20230327  2023-03-27   542.075714
1088  RD_F_J_20230328  2023-03-28   538.658953
1089  RD_F_J_20230329  2023-03-29   540.672693
1090  RD_F_J_20230330  2023-03-30   529.848539
1091  RD_F_J_20230331  2023-03-31   547.491819

[1092 rows x 3 columns]

In [ ]:
submission['answer'] = test_df['total_mean']
submission

                   ID       answer
0     TG_A_J_20230304  3117.545497
1     TG_A_J_20230305     0.000000
2     TG_A_J_20230306  3041.786728
3     TG_A_J_20230307  3194.432631
4     TG_A_J_20230308  3133.772753
...               ...          ...
1087  RD_F_J_20230327   542.075714
1088  RD_F_J_20230328   538.658953
1089  RD_F_J_20230329   540.672693
1090  RD_F_J_20230330   529.848539
1091  RD_F_J_20230331   547.491819

[1092 rows x 2 columns]

In [ ]:
submission.to_csv('scaler_ensemble_v1_1119.csv', index=False)